# Generated by Django 3.1.6 on 2021-02-07 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity', models.CharField(choices=[('Take a Walk', 'Take a Walk'), ('Listen to Music', 'Listen to Music'), ('Read a Book', 'Read a Book'), ('Play a Game', 'Play a Game'), ('Chat with Friends', 'Chat with Friends'), ('Eat Healthy Food', 'Eat Healthy Food'), ('Meditate', 'Meditate'), ('Spend Time with Family', 'Spend Time with Family'), ('Feelings', 'Feelings'), ('Just Dance', 'Just Dance'), ('Do Yoga', 'Do Yoga'), ('Have 8hrs of Sleep', 'Have 8hrs of Sleep'), ('Go Shopping', 'Go Shopping'), ('Be a Painter', 'Be a Painter'), ('Write a Story', 'Write a Story'), ('Make a Todo List', 'Make a Todo List')], max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
